"""characters_session_id_to_campaign_id

Revision ID: 1ad2ad6560f5
Revises: a2e2bb9f88cc
Create Date: 2026-02-27 11:57:42.451675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad2ad6560f5'
down_revision: Union[str, Sequence[str], None] = 'a2e2bb9f88cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('characters', sa.Column('campaign_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('characters_session_id_fkey'), 'characters', type_='foreignkey')
    op.create_foreign_key(None, 'characters', 'campaigns', ['campaign_id'], ['id'])
    op.drop_column('characters', 'session_id')
    op.add_column('combat_state', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('combat_state', 'created_at')
    op.add_column('characters', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.create_foreign_key(op.f('characters_session_id_fkey'), 'characters', 'sessions', ['session_id'], ['id'])
    op.drop_column('characters', 'campaign_id')
    op.drop_column('campaigns', 'created_at')
    # ### end Alembic commands ###
