"""Predefined level-1 character class templates for the new-adventure wizard."""

CHARACTER_PRESETS: list[dict] = [
    {
        "key": "fighter_l1",
        "label": "Fighter (level 1)",
        "character_class": "Fighter",
        "level": 1,
        "hp_max": 12,
        "hp_current": 12,
        "stats": {"STR": 16, "DEX": 12, "CON": 14, "INT": 10, "WIS": 12, "CHA": 8},
        "inventory": {"weapons": ["longsword", "shield"], "armor": "chain mail"},
    },
    {
        "key": "wizard_l1",
        "label": "Wizard (level 1)",
        "character_class": "Wizard",
        "level": 1,
        "hp_max": 6,
        "hp_current": 6,
        "stats": {"STR": 8, "DEX": 14, "CON": 12, "INT": 17, "WIS": 13, "CHA": 10},
        "inventory": {"weapons": ["quarterstaff", "dagger"], "armor": "none", "spellbook": True},
    },
    {
        "key": "rogue_l1",
        "label": "Rogue (level 1)",
        "character_class": "Rogue",
        "level": 1,
        "hp_max": 8,
        "hp_current": 8,
        "stats": {"STR": 10, "DEX": 17, "CON": 12, "INT": 12, "WIS": 11, "CHA": 14},
        "inventory": {"weapons": ["shortsword", "shortbow"], "armor": "leather", "thieves_tools": True},
    },
    {
        "key": "cleric_l1",
        "label": "Cleric (level 1)",
        "character_class": "Cleric",
        "level": 1,
        "hp_max": 8,
        "hp_current": 8,
        "stats": {"STR": 13, "DEX": 10, "CON": 14, "INT": 10, "WIS": 16, "CHA": 12},
        "inventory": {"weapons": ["mace"], "armor": "scale mail", "holy_symbol": True},
    },
    {
        "key": "ranger_l1",
        "label": "Ranger (level 1)",
        "character_class": "Ranger",
        "level": 1,
        "hp_max": 10,
        "hp_current": 10,
        "stats": {"STR": 12, "DEX": 16, "CON": 13, "INT": 10, "WIS": 14, "CHA": 10},
        "inventory": {"weapons": ["longbow", "shortsword"], "armor": "leather", "arrows": 20},
    },
]
